Postgres container added
socialappslab/denguechat-compose pull request #18
Opened 2019-06-10 04:48 UTC by FerCaz

2019-06-13 19:35 UTC, cdparra requested changes

2019-06-13 19:35 UTC, cdparra commented on README.md
> +    - Replace `ddujs2u6bpdf88` with the right name of your database.
@FerCaz ese dato del nombre de la base datos es sensible. reemplazalo por algo que se asemeje a una variable, como estaba originalmente estaba bien: `<ingresar_nombre_base_datos>`

2019-06-13 19:35 UTC, cdparra commented on docker-compose.yml
> +    - /home/fernando/Documentos/SE2/denguechat-compose/redis/redisVolume:/bitnami
De nuevo, @FerCaz es importante sacar información local. Tenés que tener un PATH genérico aquí o algo que se parezca a una variable, como estaba originalmente por ejemplo.

2019-06-13 19:35 UTC, cdparra commented on docker-compose.yml
> +  - /home/fernando/Documentos/SE2/denguetorpedo:/home/dengue/denguetorpedo
ídem que comentario anterior: `De nuevo, @FerCaz es importante sacar información local. Tenés que tener un PATH genérico aquí o algo que se parezca a una variable, como estaba originalmente por ejemplo.`

2019-06-13 19:35 UTC, cdparra commented on postgres_db/Dockerfile
> +RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
Esto me hace un poco de ruido @FerCaz. Podés explicar porque hay que poner una clave encriptada aquí?

2019-06-13 19:35 UTC, cdparra commented on postgres_db/Dockerfile
> +FROM ubuntu:16.04
Pregunta: @FerCaz no existe algún contenedor de postgres que podamos reutilizar y ya disponible en docker hub? Por ejemplo => `https://hub.docker.com/_/postgres`. Por qué no reutilizar simplemente?

2019-06-18 20:21 UTC, FerCaz commented on postgres_db/Dockerfile
> +FROM ubuntu:16.04
Me parecio que una imagen personalizada de postgres me daria mas libertad para utilizarla como necesitabamos

2019-06-18 20:23 UTC, FerCaz commented on postgres_db/Dockerfile
> +RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
De eso si no tengo idea Profesor, en la documentacion de docker que segui, requeria ingresar eso, la verdad no sabia que eso podia ser sensible

2019-07-16 22:54 UTC, cdparra approved these changes

2019-07-16 22:54 UTC, merged